text = "texts/hobbit.txt"
margin = 100
width = 1500

text_color = 0x0A0A0AFF # BLACK
bg_color = 0xFFFFF2FF   # OFF WHITE
# text_color = 0xFFFFFFFF # WHITE
# bg_color = 0x202020FF # OFF BLACK

[font]
path = "fonts/Georama-VariableFont_wdth,wght.ttf"
size = 80.0
line_height = 0.8

# add whatever OT features. they're passed as-is to shaper
features = ["smcp"]
## NOTE:
## Rustybuzz parses the string into a feature with the following format
## Possible values:
##
## - `kern` -> kern .. 1
## - `+kern` -> kern .. 1
## - `-kern` -> kern .. 0
## - `kern=0` -> kern .. 0
## - `kern=1` -> kern .. 1
## - `aalt=2` -> altr .. 2
## - `kern[]` -> kern .. 1
## - `kern[:]` -> kern .. 1
## - `kern[5:]` -> kern 5.. 1
## - `kern[:5]` -> kern ..=5 1
## - `kern[3:5]` -> kern 3..=5 1
## - `kern[3]` -> kern 3..=4 1
## - `aalt[3:5]=2` -> aalt 3..=5 1

# variations specific to Raqq.ttf
# replace with the axis in your font
[[font.variations]]
name = "wdth"
min = 70
max = 150
rest = 100

[[font.variations]]
name = "wght"
min = 300
max = 300
rest = 300
