text = "texts/roboto_readme.txt"
margin = 100
width = 2000

text_color = 0x0A0A0AFF # BLACK
bg_color = 0xFFFFF2FF   # OFF WHITE
# text_color = 0xFFFFFFFF # WHITE
# bg_color = 0x202020FF # OFF BLACK

[font]
path = "fonts/RobotoSerif[grad,opsz,wdth,wgth].ttf"
size = 80.0
line_height = 1.25

# untested
# add whatever OT features. they're passed as-is to shaper
# features = ["ss02"]

# variations specific to Raqq.ttf
# replace with the axis in your font
[[font.variations]]
name = "wdth"
min = 50
max = 150
rest = 100
